$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: fastapi-ml-deployment
endpoint_name: fastapi-ml-endpoint

code_configuration:
  code: .  # Points to the FastAPI code directory
  scoring_script: score.py  # FastAPI entry file
  
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: environment.yaml  # Specifies dependencies
  
instance_type: Standard_DS3_v2  # Move it here

instance_count: 3
