name: Deploy FastAPI to Azure ML Managed Endpoint

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Azure CLI and ML extension
        run: |
          pip install azure-ai-ml
          az login --service-principal \
            --username $(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientId) \
            --password $(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .clientSecret) \
            --tenant $(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .tenantId)
          az account set --subscription $(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)
          az configure --defaults group=${{ secrets.AZURE_RESOURCE_GROUP }} workspace=${{ secrets.AZURE_WORKSPACE_NAME }}

      - name: Check if Endpoint Exists
        id: check-endpoint
        continue-on-error: true  # Prevents failure if endpoint doesn't exist
        run: |
          if az ml online-endpoint show --name fastapi-ml-endpoint --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }} >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_ENV
            echo "Endpoint 'fastapi-ml-endpoint' already exists." >> $GITHUB_STEP_SUMMARY
          else
            echo "exists=false" >> $GITHUB_ENV
            echo "Endpoint 'fastapi-ml-endpoint' does not exist. It will be created." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Deploy Endpoint (Only if it doesn’t exist)
        if: env.exists == 'false'
        run: |
          echo "Creating new endpoint: fastapi-ml-endpoint"
          az ml online-endpoint create --name fastapi-ml-endpoint --file endpoints.yml
      
      - name: Log if Endpoint Exists
        if: env.exists == 'true'
        run: echo "Endpoint 'fastapi-ml-endpoint' already exists. No need to create it."
        
      - name: Deploy or Update Service
        run: |
          if az ml online-deployment show --name fastapi-ml-deployment --endpoint fastapi-ml-endpoint --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }}; then
            az ml online-deployment update --name fastapi-ml-deployment --endpoint fastapi-ml-endpoint --file deployment.yml
          else
            az ml online-deployment create --name fastapi-ml-deployment --endpoint fastapi-ml-endpoint --file deployment.yml --all-traffic
          fi
