name: Deploy FastAPI to Azure ML Managed Endpoint

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the GitHub Actions runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pulls the latest code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Ensures correct Python version

      - name: Install Azure CLI and ML extension
        run: |
          pip install azure-ai-ml  # Install Azure ML CLI tools
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az configure --defaults group=${{ secrets.AZURE_RESOURCE_GROUP }} workspace=${{ secrets.AZURE_WORKSPACE_NAME }}

      - name: Deploy Azure ML Managed Online Endpoint
        run: |
          az ml online-endpoint create --name fastapi-ml-endpoint --file endpoints.yaml || echo "Endpoint already exists"

      - name: Deploy FastAPI service
        run: |
          az ml online-deployment create --name fastapi-ml-deployment \
            --endpoint fastapi-ml-endpoint \
            --file deployment.yaml --all-traffic
