name: Deploy FastAPI to Azure ML Managed Endpoint

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the GitHub Actions runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pulls the latest code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Ensures correct Python version

      - name: Install Azure CLI and ML extension
        run: |
          pip install azure-ai-ml  # Install Azure ML CLI tools
          echo '${{ secrets.AZURE_CREDENTIAL }}' > azure_config.json
          AZURE_CLIENT_ID=$(jq -r '.clientId' azure_config.json)
          AZURE_CLIENT_SECRET=$(jq -r '.clientSecret' azure_config.json)
          AZURE_TENANT_ID=$(jq -r '.tenantId' azure_config.json)
          AZURE_SUBSCRIPTION_ID=$(jq -r '.subscriptionId' azure_config.json)
          AZURE_RESOURCE_GROUP=$(jq -r '.resourceGroup' azure_config.json)
          AZURE_WORKSPACE_NAME=$(jq -r '.workspaceName' azure_config.json)

          az login --service-principal --username "$AZURE_CLIENT_ID" \
            --password "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"

          az account set --subscription "$AZURE_SUBSCRIPTION_ID"
          az configure --defaults group="$AZURE_RESOURCE_GROUP" workspace="$AZURE_WORKSPACE_NAME"

      - name: Deploy Azure ML Managed Online Endpoint
        run: |
          az ml online-endpoint create --name fastapi-ml-endpoint --file endpoints.yaml || echo "Endpoint already exists"

      - name: Deploy FastAPI service
        run: |
          az ml online-deployment create --name fastapi-ml-deployment \
            --endpoint fastapi-ml-endpoint \
            --file deployment.yaml --all-traffic
